### ISSUE TITLE
Trial Balance refuses a valid transaction

### ISSUE THREAD

**Issue by DedrickEnc** [IMA-WorldHealth/bhima#748] opened 2015-09-17 14:47 UTC
the trans_id HBB2446 is good but can not pass to the trial balance.

**Comment by jniles** [comment] 2015-09-17 15:39
HBB2446 is reported as missing a deb_cred_uuid, for deb_cred_type = `C`.  Can you give me steps to reproduce?  My trial balance is refusing to post it.

See below
![hbb2446](https://cloud.githubusercontent.com/assets/896472/9937894/987c5b32-5d5a-11e5-964f-96e53d3b6722.png)

**Comment by jniles** [comment] 2015-09-17 15:39
(There definitely is a bug in the filter though)

**Comment by jniles** [comment] 2015-09-22 07:33
Closing this as it is not a bug.  Transaction HBB2446 is not a valid transaction, and therefore cannot be posted.  The error reported is that we are missing a deb_cred_uuid, but have a deb_cred_type.

If you use the editing capabilities of the journal, and remove the faulty deb_cred_type, then the transaction balances with only a warning.

**Closed by jniles** 2015-09-22 07:33 UTC
Labels: bug

**Comment by jniles** [comment] 2015-09-24 09:33
For reference, the filter issues were closed in #756 .
